version: '3.7'
services:
  backend:
    build:
      ./backend
    networks:
      - tp1-network
    depends_on:
      - database
  database:
    build:
      ./database
    networks:
      - tp1-network
    volumes:
      - /database:/var/lib/postgresql/data
  httpd:
    build:
      ./frontend
    ports:
      - 80:80
    networks:
      - tp1-network
    depends_on:
      - backend
networks:
  tp1-network: