name: CI devops 2022 CPE
on:
  workflow_call:
      inputs:
        path:
          required: true
          type: string
        docker_name:
          required: true
          type: string
        
jobs:
  build-and-push-docker-image:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ${{inputs.path}}
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/${{inputs.docker_name}}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}