# jobs:
#   build-and-push-docker-image:
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Login to DockerHub
#         run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
#       - name: Build image and push backend
#         uses: docker/build-push-action@v2
#         with:
#           # relative path to the place where source code with Dockerfile is located
#           context: ${{inputs.path}}
#           # Note: tags has to be all lower-case
#           tags: ${{secrets.DOCKER_USERNAME}}/${{inputs.docker_name}}
#           # build on feature branches, push only on main branch
#           push: ${{ github.ref == 'refs/heads/main' }}
name: CI devops 2022 CPE
on:
  workflow_call:
    secrets: # requiring secrets
      SONAR_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true         

jobs:  
  build-and-push-backend:
    runs-on: ubuntu-latest
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./TP01/backend
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/tp-devops-cpe-backend
           # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
  build-and-push-database:
    runs-on: ubuntu-latest
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub      
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Build image and push database
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./TP01/database
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/tp-devops-cpe-database
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
      
  build-and-push-httpd:
    runs-on: ubuntu-latest
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Build image and push httpd
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./TP01/httpd
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/tp-devops-cpe-httpd
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
  build-and-push-fronted:
    runs-on: ubuntu-latest
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Build image and push frontend  
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./TP03/front
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/tp-devops-cpe-frontend
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}