name: CI devops 2022 CPE main
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: 
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    # steps to perform in job
    steps:
      - uses: ./.github/workflows/.test.yml
    