name: CI devops 2022 CPE
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: 
      - main
  pull_request:

jobs:
  #define job to build and publish docker image of backend
  build-and-push-backend:
    # run only when code is compiling and tests are passing
    needs: test-backend
    runs-on: ubuntu-latest
    # steps to perform in job
    steps:
      - uses: ./.github/workflows/.production.yml
        with:
          path: "./TP01/backend"
          docker_name: "tp-devops-cpe-backend"
    #define job to build and publish docker image of backend
  build-and-push-database:
    runs-on: ubuntu-latest
    # steps to perform in job
    steps:
      - uses: ./.github/workflows/.production.yml
        with:
          path: "./TP01/database"
          docker_name: "tp-devops-cpe-database"
    #define job to build and publish docker image of backend
  build-and-push-httpd:
    runs-on: ubuntu-latest
    # steps to perform in job
    steps:
      - uses: ./.github/workflows/.production.yml
        with:
          path: "./TP01/httpd"
          docker_name: "tp-devops-cpe-httpd"
  build-and-push-frontend:
    runs-on: ubuntu-latest
    # steps to perform in job
    steps:
      - uses: ./.github/workflows/.production.yml
        with:
          path: "./TP03/frontend"
          docker_name: "tp-devops-cpe-httpd"